### ISSUE TITLE
Category findByID

### ISSUE THREAD

**Issue by traineratoss** [traineratoss/AIMSServer2023#11]
https://github.com/traineratoss/AIMSServer2023/blob/4cb6b1720330f27cdbf3506cf5d6dc3d0a7dd2d5/src/main/java/com/atoss/idea/management/system/repository/CategoryRepository.java#L11

Please use the default method provided by the CRUDRepository.

**Comment by DragosBrex** [comment]
#11 Replaced "findCategoryById()" with default CRUDRepository method "findById()", made necessary changes (Optional get() and isPresent())
CR: Alexandra M, Rares T
