### ISSUE TITLE
Idea findByID

### ISSUE THREAD

**Issue by traineratoss** [traineratoss/AIMSServer2023#12]
https://github.com/traineratoss/AIMSServer2023/blob/4cb6b1720330f27cdbf3506cf5d6dc3d0a7dd2d5/src/main/java/com/atoss/idea/management/system/repository/IdeaRepository.java#L13

Please use the default method provided by CRUDRepository.

**Comment by DragosBrex** [comment]
#12 Replaced "findIdeaById()" with default CRUDRepository method "findById()", made necessary changes (Optional get() and isPresent())
CR: Alexandra M, Rares T
